### PR TITLE
Flesh out the ships

### PR DESCRIPTION
**Pull request by Shipmaster001**
I will be adding flavor text to the Ships and Goals in this expansion deck.I have also added powers to the Changeling Takeover and Banished to Another Dimension Ships. I hope that this won't be a problem. :)

### CODE REVIEW

**Comment by marco262** [comment]
Feel free to make any changes you like, but please keep it in your own repo.

**Comment by marco262** [comment]
Let me know if you need help figuring out how to fork a repository.

**Comment by Shipmaster001** [comment]
I'm sorry. I don't know how to do that.

**Comment by marco262** [comment]
Simply go to the top-right of the repo page, and click the Fork button. Select the Github account you want the repo saved under. That's it!

You will want to save your changes manually ahead of time, and recommit them in your fork.

See this page for more info: https://help.github.com/articles/fork-a-repo/

**Comment by Shipmaster001** [comment]
Would it be all right if I copied and pasted the code? If there's a better and/or more legal method of putting the changes in my repo, please say so.

**Comment by marco262** [comment]
All our code on Github is open source, so you're allowed to do whatever you like with it. Just make sure to always assign credit when due, and provide links back to the original code/assets when possible.

**Comment by Shipmaster001** [comment]
Okay, I think I have all of the code on my repository, so I'm won't be trying to force it down your throat again, but I have just one more question. How did you get the art on your website? The code didn't tell me how that happened, and the card images didn't register my changes.

**Comment by marco262** [comment]
The images are created using CardMachine, which is in a separate repo here: https://github.com/HorriblePeople/CardMachine
The cards.pon file you're editing is used as an input for that program, which spits out the card images.

Honestly, unless you have good Python knowledge and a lot of patience, I wouldn't recommend trying to get that working on your own machine. Instead, your best bet is to plug the card text in manually one at a time to a card generator, like this one: http://latent-logic.github.io/TSSSF-Frontend/

**Pull request closed without merging**
